version: '3'
services:
  profittrailer:
    container_name: profittrailer
    image: "doccie/profittrailer:latest"
    volumes:
      - /home/doccie/.profittrailer/data:/app/ProfitTrailer/data
      - /home/doccie/.profittrailer/application.properties:/app/ProfitTrailer/application.properties
    restart: unless-stopped
    ports:
      - "8081:8081"
